Gallery1/Gallery1/Models/PhotoArt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Gallery1.Models
{
    public class PhotoArt
    {
        private int photoId;

        public int Id { get; set; }
        public string PhotoName { get; set; }
        public string Photo { get; set; }

        public ICollection<ArtWork> ArtWorks { get; set; }

        public PhotoArt(string v, string fileName)
        {
            ArtWorks = new List<ArtWork>();
        }

        public PhotoArt()
        {
        }

        public PhotoArt(int photoId)
        {
            this.photoId = photoId;
        }
    }
}

Gallery1/Gallery1/Controllers/PhotoArtController.cs
using Gallery1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gallery1.Controllers
{
    public class PhotoArtController : Controller
    {

        [HttpGet]
        public ActionResult UploadPhoto()
        {
            return View();
        }

        public ActionResult UploadPhoto(HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                upload.SaveAs(Server.MapPath("~/Files/" + fileName));
                int photoId;
                using (ArtContext db1 = new ArtContext())
                {
                    PhotoArt p1 = new PhotoArt { PhotoName = fileName, Photo = Server.MapPath("~/ Files / " + fileName) };
                    db1.PhotoArts.Add(p1);
                    db1.SaveChanges();
                    photoId = p1.Id;
                }
            }

            return RedirectToAction("UploadPhoto");
        }
    }
}

Gallery1/Gallery1/Views/PhotoArt/UploadPhoto.cshtml
@{
    ViewBag.Title = "UploadPhoto";
}

@model Gallery1.Models.PhotoArt
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Новое фото</h2>
@using (Html.BeginForm("UploadPhoto", "PhotoArt", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="second_col">
        <div class="form-group">
            <div style="position:relative;">
                <label>Картинка</label>
                <a class='btn' href='javascript:;'>
                    Выберите файл...
                    <input name="upload" type="file" size="40"
                           style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                           onchange='$("#upload-file-info").html($(this).val());'>
                </a>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
        </div>
    </div>

    <input type="submit" value="Отправить" class="btn btn-primary" />
}